apiVersion: v1
kind: Pod
metadata:
   name: myapp-prod
   labels:
    tier: frontend
    app: myapp
    env: prod
  
spec:
  containers:
  - image: stefanprodan/podinfo
    name: myapp-podinfo-container
    ports:
      - containerPort: 9898